spring:
  application:
    name: spring-boot

  mvc:
    log-request-details: true
    log-resolved-exception: true
    static-path-pattern: /static/**

  web:
    resources:
      static-locations:
        - classpath:/static/

logging:
  level:
    root: info
    web: debug
    org.springframework.web: trace
