spring:
  application:
    name: spring-data-common
  datasource:
    url: jdbc:mysql://localhost:3306/demofx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: example
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      pool-name: pool-sdc
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true

person:
  id: 123
  first-name: jini
  last-name: yoo
